# -*- coding: utf-8 -*-
"""grangercausalitytests.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13aZlblWrwpePQSB4m5BkVtaYmxBfPqli

# 라이브러리 설치 및 import
"""

!pip install --upgrade pandas
!pip install --upgrade pandas-datareader

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller

"""# 데이터 로드"""

# 이재명 후보
rate = pd.read_csv('granger_data_no1.csv', encoding="cp949")
# 윤석열 후보 'granger_data_no2.csv'

rate['date'] = pd.to_datetime(rate['date'])
rate.set_index('date', inplace=True)
rate

cols = rate.columns
cols

"""# 정상성

*   정상성/비정상성 확인

  ADF < Critical Value  
  or  
  p-value < 신뢰수준값

  --> 두 조건 중 하나 이상 만족하면 정상성 데이터
"""

def adf(inputSeries):
  result = adfuller(inputSeries)
  print('ADF: %f' % result[0])
  print('p-value: %f' % result[1])
  print('Critical Values:')
  for key, value in result[4].items():
    print('\t%s: %.3f' % (key, value))

for col in cols:
  print('<', col, '>')
  adf(rate[col])

"""

*   정상성 확보

"""

def difference(dataset, interval=1):
  diff = [0]
  for i in range(interval, len(dataset)):
    value = dataset[i] - dataset[i-interval]
    diff.append(value)
  return np.array(diff)

diff1_cols = ['rate', '이재명', '윤석열', '민주당', '특검', '박근혜',
              '북한', '부동산', '여론조작', '대선후보', '세금',
              '감옥', '게이트', '단일화', '유승민', '안철수',
              '정책', '선거', '지지율', '사기', '자영업자',
              '김건희', '무당', '도박', '페미', '토론', '김혜경']

diff2_cols = ['특검', '박근혜', '여론조작', '세금', '안철수',
              '정책', '지지율', '김건희', '무당', '페미', '김혜경']

diff3_cols = ['특검', '박근혜', '여론조작', '무당', '김혜경']

diff4_cols = ['특검', '여론조작', '무당']

diff5_cols = ['여론조작', '무당']

diff6_cols = ['여론조작']

for col in diff1_cols:
  rate[col] = difference(rate[col])

for col in diff2_cols:
  rate[col] = difference(rate[col])

for col in diff3_cols:
  rate[col] = difference(rate[col])

for col in diff4_cols:
  rate[col] = difference(rate[col])

for col in diff5_cols:
  rate[col] = difference(rate[col])

for col in diff6_cols:
  rate[col] = difference(rate[col])

rate

"""

*   정상성 데이터 저장

"""

rate.to_csv('no1-diff.csv', index=False, encoding='utf-8-sig')

"""

*   데이터 확인

"""

keyword = '대장동'
x = rate.index

fig = plt.figure(figsize = (10,6))
ax1 = fig.add_subplot()

ax1.plot(x,rate['rate'], color = 'b')
ax2 = ax1.twinx()
ax2.plot(x,rate[keyword], color = 'k')
plt.show()

"""# Granger Causality"""

cols = rate.columns[1:]
for col in cols:
  raw = pd.concat([rate['rate'], rate[col]], axis=1)
  # Granger Causality 테스트
  print('\n[', raw.columns[1], '-> 지지율 ]') # [1]이 [0]의 원인인지
  granger_result1 = sm.tsa.stattools.grangercausalitytests(raw.diff(1).dropna().values, maxlag=6, verbose=True)

"""# 이재명
*   [F-test] 신뢰도 95% 이상: 대장동, 이낙연, 국회, 부동산, 여론조작, 대선후보, 정책, 토론
*   [F-test] 신뢰도 90% 이상: 특검, 대장동, 이낙연, 국회, 부동산, 여론조작, 대선후보, 게이트, 유승민, 조작, 정책, 토론
*   [Chi2-test] 신뢰도 95% 이상

# 윤석열

*   [F-test] 신뢰도 95% 이상: 특검, 대장동, 박근혜, 이낙연, 국회, 부동산, 여론조작, 대선후보, 안철수, 정책, 자영업자, 토론
*   [F-test] 신뢰도 90% 이상: 특검, 사퇴, 홍준표, 대장동, 박근혜, 이낙연, 검찰, 국회, 부동산, 여론조작, 대선후보, 정권교체,  안철수, 정책, 김종인, 교체, 연기, 자영업자, 토론
*   [Chi2-test] 신뢰도 95% 이상:
"""